from iprs_status_codes_list import status_codes as iprs_status_codes

world_divisions_and_attached_fields = {
    "ECD": "East-Central Africa Division",
    "EUD": "Inter-European Division",
    "IAD": "Inter-American Division",
    "IF": "Israel Field",
    "MENAUM": "Middle East and North Africa Union Mission",
    "NAD": "North American Division",
    "NSD": "Northern Asia-Pacific Divsion",
    "SAD": "South American Division",
    "SPD": "South Pacific Division",
    "SID": "Southern Africa-Indian OCean Division",
    "SUD": "Southern Asia Division",
    "SSD": "Southern Asia-Pacific Division",
    "TED": "Trans-European Division",
    "UUC": "Ukranian Union Conference",
    "WAD": "West-Central Africa Divsion",
}


general_conference_deprartments_and_services = {
"AAIM": "Adventist AIDS International Ministry",
    "ACM": "Adventist Chaplaincy Ministries",
    "ADRA": "Adventist Development and Relief Agency International",
    "AM": "Adventist Mission",
    "AR": "Adventist Review",
    "ARM": "Adventist Risk Management",
    "ARMies": "Adventist Review Ministries",
    "ASTR": "Archives, Statistics, and Research",
    "AWR": "Adventist World Radio",
    "BRI": "Biblical Research Institute",
    "CHM": "Children's Research Institute",
    "COM": "Communication",
    "EDU": "Education",
    "FM": "Family Ministries",
    "GCAS": "General Conference Auditing Services",
    "GRI": "Geoscience Research Institute",
    "HC": "Hope Channel, Inc",
    "HM": "Health Ministries",
    "HR": "Human Resources",
    "IHO": "In-House Operation",
    "IPRS": "International Personnel Resources and Services",
    "ITS": "Information Technology Services",
    "MIN": "Ministerial Association",
    "OGC": "Office of General Counsel",
    "PARL": "Public Affairs and Religious Liberty",
    "PCM": "Public Campus Ministries",
    "PRE": "Presidential",
    "PUB": "Publishing Ministries",
    "SEC": "Secretariat",
    "SSPM": "Sabbath School and Personal Ministries",
    "SW": "Stewardship Ministries",
    "TRE": "Treasury",
    "TRS": "Planned Giving and Trust Services",
    "WHT": "Ellen White Estate, Inc",
    "WM": "Women's Ministries",
    "YOU": "Youth Ministries",
}

general_conference_committees_and_boards = {
     "AAA": "Accrediting Association of Seventh-day Adventist Schools, Colleges, and Universities (GCC)",
    "ABSGManuEval": "Adult Bible Study Guide Manuscript Evaluating Committee (ADCOM-S)",
    "AAIMBd": "Adventist AIDS International Ministry Board (ADCOM-B)",
    "ADRABd": "Adventist Development and Relief Agency Board",
    "ASICoordCom": "Adventist-Laymen’s Services and Industries (ASI) Coordinating Committee (GCC-S)",
    "AMSCom": "Adventist Membership Systems Committee (ADCOM-S)",
    "AMiCUS": "Adventist Ministry to College and University Students Committee (ADCOM-S)",
    "ARMiesBd": "Adventist Review Ministries Publishing Board (GCC-B)",
    "ARMBd": "Adventist Risk Management Board",
    "AUABdofT": "Adventist University of Africa Board of Trustees (GCC-B)",
    "AWPubBd": "Adventist World Publishing Board (GCC-B)",
    "AWRBd": "Adventist World Radio Board",
    "AmicusCuria": "Amicus Curia Committee (ADCOM-S)",
    "ASTRCOM": "Archives, Statistics, and Research Statistics Committee (ADCOM-S)",
    "BRICOM": "Biblical Research Institute Committee (ADCOM-S)",
    "BRIOC": "Biblical Research Institute Operating Committee (ADCOM-S)",
    "CRC": "Candidate Review Committee (ADCOM-S)",
    "Adhoc": "Central African Union Mission Survey Commission (ADCOM-A)",
    "CSSYC": "Children, Sabbath School, and Youth Resource Coordinating Committee (ADCOM-S)",
    "Adhoc": "Chinese Union Mission Survey Commission (ADCOM-A)",
    "ChMan": "Church Manual Committee (ADCOM-S)",
    "ComSabAdvDenom": "Committee for Outreach to Sabbatarian Adventist Denominations (ADCOM-S)",
    "SDAHProfEd": "Committee on Seventh-day Adventist Health Professional Education (IBE-Ssub)",
    "COC": "Community Outreach Committee (ADCOM-S)",
    "Con&By": "Constitution and Bylaws Committee (ADCOM-S)",
    "CIIA": "Council on Interchurch/Interreligion Affairs (ADCOM-S)",
    "CPlan": "Council Planning Committee (ADCOM-S)",
    "Cred&L": "Credentials and Licenses Committee (ADCOM-S)",
    "PrivGovCom": "Data Privacy Governance Committee (ADCOM-S)",
    "DefMPC": "Defense of Members Persecuted for Religious Reasons Committee (ADCOM-S)",
    "EEAffC": "Eastern Europe Affairs Committee (ADCOM-S)",
    "EE&CIRC": "Employment Ethics and Conflict of Interest Review Committee (ADCOM-S)",
    "ESDAEB": "Encyclopedia of Seventh-day Adventists Editorial Board (ADCOM-S)",
    "ESDAEB-ADCOM": "Encyclopedia of Seventh-day Adventists Editorial Board: Administrative Committee (ADCOM-S)",
    "ESDA-EDCOM": "Encyclopedia of Seventh-day Adventist Editorial Committee (ADCOM-S)",
    "Faith&ScCou": "Faith and Science Council (ADCOM-S)",
    "FinStateRev": "Financial Statement Review Committee (ADCOM-S)",
    "FrMedAdv": "French Media Advisory Committee",
    "FPWG": "Future Plans Working Group (ADCOM-S)",
    "ADCOM": "General Conference Administrative Committee (GCC-S)",
    "GCACMCom": "General Conference Adventist Chaplaincy Ministries Committee (ADCOM-S)",
    "GCDO": "General Conference and Division Officers",
    "AudCom": "General Conference Audit Committee (GCC-S)",
    "GCASBd": "General Conference Auditing Service Board",
    "GCBioCom": "General Conference Bioethics Committee (ADCOM-S)",
    "GCCanJMAMCom": "General Conference-Canadian Joint Ministries Agreement Management Committee (ADCOM-S)",
    "DistBelCC": "General Conference Compliance Review Committee with Distinctive Beliefs of Seventh-day Adventist Church for Church Organizations and Institutions (ADCOM-S)",
    "HomosexualityCC": "General Conference Compliance Review Committee with Doctrine, Policies, Statements, and Guidelines for Church Organizations and Institutions Regarding Homosexuality (ADCOM-S)",
    "OrdinationCC": "General Conference Compliance Review Committee with Doctrine, Policies, Statements, and Guidelines for Church Organizations and Institutions Regarding Issues of Ordination (ADCOM-S)",
    "CreationCC": "General Conference Compliance Review Committee with Doctrine, Policies, Statements, and Guidelines for Church Organizations and Institutions Teaching Creation/Origins (ADCOM-S)",
    "CorePolCC": "General Conference Compliance Review Committee with General Conference Core Policies (S 90) (ADCOM-S)",
    "GCCI&BSC": "General Conference Corporate Identity and Building Signage Committee (ADCOM-S)",
    "Corp": "General Conference Corporation Board of Directors",
    "GCDCCS": "General Conference Development and Construction Consulting Service (ADCOM-S)",
    "GCC": "General Conference Executive Committee",
    "GCFacUse": "General Conference Facilities Use for Special Events Clearing Committee (ADCOM-S)",
    "GCGradSchFund": "General Conference Graduate Scholarship Fund Committee (ADCOM-S)",
    "HPL&AirLiabInsC": "General Conference Hospital Professional Liability (HPL) and Aircraft Liability Insurance Committee (GCC-S)",
    "GCIMTECom": "General Conference Institutions Ministerial and Theological Education Committee (ADCOM-S)",
    "IMC": "General Conference Investment Management Committee (Corp-Ssub)",
    "GCLC": "General Conference Leadership Council (ADCOM-S)",
    "GCMB": "General Conference Mission Board (GCC-B)",
    "GCMCLC": "General Conference Music in Church Life Committee (ADCOM-S)",
    "GCNon-ExCom": "General Conference Non-Exempt Compensation Committee (ADCOM-S)",
    "Ad hoc": "General Conference Session 2025 Venue Selecting Steering Committee (ADCOM-A)",
    "GCSPlan": "General Conference Session Planning Committee (ADCOM-S)",
    "GENCOSUD": "General Conference, Southern Asia Division Committee (GCC-S)",
    "TMC": "General Conference Trust Management Committee (Corp-S)",
    "GRICOM": "Geoscience Research Institute Committee (ADCOM-S)",
    "GRIOC": "Geoscience Research Institute Operating Committee (ADCOM-S)",
    "GLTAB": "Global Leadership Training Advisory Board (ADCOM-S)",
    "GMIC": "Global Mission Issues Committee (ADCOM-S)",
    "Ad hoc Growing Together—Spirit of Prophecy Family Set Committee": "ADCOM-A",
    "HCBd": "Hope Channel, Inc Board",
    "HRC": "Human Resources Committee (ADCOM-S)",
    "ITSCom": "Information Technology Services Committee (ADCOM-S)",
    "IHBudCom": "In-House Budget Committee (ADCOM-SSub)",
    "IPABd": "Institute for the Prevention of Addictions Board (ADCOM-B)",
    "IWMC": "Institute of World Mission Council (ADCOM-S)",
    "IABCS": "International Association of Bible Correspondence Schools (ADCOM-S)",
    "IBMCCom": "International Bible and Mission Conference Committee (ADCOM-S)",
    "IBE": "International Board of Education (GCC-B)",
    "IBMTE": "International Board of Ministerial and Theological Education (GCC-B)",
    "ICC": "International Crisis Committee (ADCOM-S)",
    "IHTAExCou": "International Health and Temperance Association Executive Council (GCC)",
    "IRLABd": "International Religious Liberty Association Board",
    "ISEPol": "International Service Employee Policy Review and Development Committee (GCMB-Ssub)",
    "IFOC": "Israel Field Oversight Committee (ADCOM-S)",
    "LegalAff": "Legal Affairs Committee (ADCOM-S)",
    "MCIC": "Media-Communication Committee (ADCOM-S)",
    "MENAOC": "Middle East and North Africa Union Mission Oversight Committee (ADCOM-S)",
    "MinPubAdvC": "Ministry Publishing Advisory Committee (ADCOM-S)",
    "PKCom": "Ministry to Pastors’ Kids Committee (ADCOM-S)",
    "MALC": "Mission Advance Leadership Committee (ADCOM-S)",
    "MBSFC": "Mission Board Strategy and Funding Committee (GCMB-Ssub)",
    "MPPC": "Mission Personnel Processing Committee (GCMB-Ssub)",
    "MTCCom": "Mission to the Cities Committee (ADCOM-S)",
    "Worship": "Morning Worship Committee (ADCOM-S)",
    "Ad hoc Netherlands Union Conference Survey Commission": "ADCOM-A",
    "N&RComm": "Nurture and Retention Committee (ADCOM-S)",
    "OSACom": "Office Space Allocation Committee (ADCOM-S)",
    "PIHOC": "Plant and In-House Operations Committee (ADCOM-S)",
    "PolRev&Dev": "Policy Review and Development Committee (ADCOM-S)",
    "PrayMinCom": "Prayer Ministries Committee (ADCOM-S)",
    "PREXAD": "President’s Executive Administrative Council",
    "Protocol": "Protocol Committee (ADCOM-S)",
    "PARLAffN": "Public Affairs and Religious Liberty Affairs Committee-General Conference/North American Division (Congressional Affairs) (ADCOM-S)",
    "PARLWrldAff": "Public Affairs and Religious Liberty World Affairs Committee-General Conference (ADCOM-S)",
    "POSCom": "Public and Official Statements Committee (ADCOM-S)",
    "R&RCom": "Revival and Reformation Committee (ADCOM-S)",
    "SSCurRevAdv": "Sabbath School Curriculum Review and Advisory Committee (ADCOM-S)",
    "SSManuEval": "Sabbath School Manuscript Evaluating Committee (SSPub-Ssub)",
    "SSPubBd": "Sabbath School Publications Board (ADCOM-B)",
    "SNMC": "Special Needs Ministries Committee (ADCOM-S)",
    "Ad hoc Special Needs Ministries Taskforce for Caregivers": "SNMC-S",
    "Ad hoc Special Needs Ministries Taskforce for Mental Health/Disabilities": "SNMC-S",
    "Ad hoc Special Needs Ministries Taskforce for Orphan Ministries": "SNMC-S",
    "Ad hoc Special Needs Ministries Taskforce for Physical Mobility/Disabilities": "SNMC-S",
    "Ad hoc Special Needs Ministries Taskforce for the Blind": "SNMC-S",
    "Ad hoc Special Needs Ministries Taskforce for the Deaf": "SNMC-S",
    "SpProph": "Spirit of Prophecy Committee (ADCOM-S)",
    "SP&B": "Strategic Planning and Budgeting Committee (GCC-S)",
    "ADCOM-A": "Ad hoc SUD and Lowry Property Review Committee",
    "Total Member Involvement Council (ADCOM-S)": "TMICouncil",
    "ADCOM-A": "Ad hoc Trans-Caucasus Union Mission Survey Commission",
    "ADCOM-A": "Ad hoc Union of Churches Study Committee",
    "United Nations Liaison Committee (ADCOM-S)": "UNLC",
    "ADCOM-A": "Ad hoc Unity Oversight Committee",
    "ADCOM-A": "Ad hoc Visitor’s Experience Committee",
    "Week of Prayer Reading Committee (ADCOM-S)": "WPRead",
    "ADCOM-A": "Ad hoc West Indonesia Union Mission Survey Commission",
    "World Sabbath School Bible Study Guide Curriculum Committee (GCC-S)": "WSSCC",
    "ADCOM-A": "Ad hoc Zimbabwe Union Conference Survey Commission",
}

general_conference_common_meetings = {
     "EOM": "Executive Officers Meeting",
    "GCS": "General Conference Session",
    "PreC": "Presidents Council (General Conference and Division Presidents)",
    "SecC": "Secretaries Council (General Conference and Division Secretaries)",
    "TreC": "Treasurers Council (General Conference and Division Treasurers)"
}



general_conference_acronyms = [world_divisions_and_attached_fields, general_conference_deprartments_and_services, general_conference_committees_and_boards, general_conference_common_meetings, iprs_status_codes]