api_url = "https://orgmast.adventist.org/OrgMastAPI/api/OMAdmfield?$filter=Active%20eq%20true"

division_dict = {
    0: ("East-Central Africa Division", "ECD"),
    1: ("Euroasia Division", "ESD"),
    2: ("Intereuropean Division", "EUD"),
    3: ("Interamerican Division", "IAD"),
    4: ("North American Division", "NAD"),
    5: ("Northern Asia Pacific Division", "NSD"),
    6: ("South American Division", "SAD"),
    7: ("South Pacific Division", "SPD"),
    8: ("Southern African Indian Ocean Division", "SID"),
    9: ("Southern Asia Division", "SUD"),
    10: ("Southern Asia Pacific Division", "SSD"),
    11: ("Transeuropean Division", "TED"),
    12: ("West Central Africa Division", "WAD"),
    13: ("Chinese Union Mission", "CHUM"),
    14: ("Middle East North African Union Mission", "MENAUM"),
}
union_dict = {
    0: ("Burundi Union Mission", "BURM"),
    1: ("East Kenia Union Conference", "EAKU"),
    2: ("East Congo Union Mission", "ECUM"),
    3: ("Eastern Ethiopian Union Mission", "ENET"),
    4: ("North East Congo Union Mission", "NECO"),
    5: ("Northern Tanzania Union Mission", "NTAU"),
    6: ("Rwanda Union Mission", "RWUM"),
    7: ("Suthern Tanzania Union Mission", "STAU"),
    8: ("Uganda Union Mission", "UGUM"),
    9: ("West Congo Union Mission", "WCUM"),
    10: ("West Kenya Union Conference", "WKEU"),
    11: ("Western Ethiopia Union Mission", "WNET"),
    12: ("South Sudan Attached Territory", "SSAT"),
    13: ("Eritea Mission Field", "EMF"),
    14: ("Belarus Union of Churches", "BELC"),
    15: ("Caucasus Union Mission", "CAUU"),
    16: ("East Russian Union Mission", "ERUM"),
    17: ("Far Eastern Union of Chruches Mission", "FEC"),
    18: ("Moldova Union of Churches Conference", "MOUC"),
    19: ("Southern Union Mission", "ESUC"),
    20: ("West Russian Union Mission", "WRUC"),
    21: ("Armenian Field", "ARMN"),
    22: ("Crimea Field", "CRIM"),
    23: ("Don Field", "EUKC"),
    24: ("Georgian Field", "GEGN"),
    25: ("Austrian Union", "AUOC"),
    26: ("Bulgarian Union", "BUOC"),
    27: ("Czecho-SLovak Union", "CSUC"),
    28: ("Franco-Belgian Union", "FBUC"),
    29: ("Italian Union", "IUOC"),
    30: ("North German Union", "NGUC"),
    31: ("Portuguese Union", "PUOC"),
    32: ("Romanian Union", "RMUC"),
    33: ("South German Union", "SGUC"),
    34: ("Spanish Union", "SUOC"),
    35: ("Swiss Union", "SWSC"),
    36: ("Atlantic Caribbean Union", "ATCA"),
    37: ("Belize Union", "BELM"),
    38: ("Caribbean Union", "CRUC"),
    39: ("Central Mexican Union", "CMUM"),
    40: ("Chiapas Mexican Union", "SMUC"),
    41: ("Cuban Union", "CUUC"),
    42: ("Dominican Union", "DMUM"),
    43: ("Dutch Caribbean Union", "DUTC"),
    44: ("East Venezuela Union", "EVAU"),
    45: ("El Salvador Union", "ELSA"),
    46: ("French-Antilles-Guiana Union", "FAGUM"),
    47: ("Guatemala Union", "NCAU"),
    48: ("Haitian Union", "HAUM"),
    49: ("Honduras Union", "MCAU"),
    50: ("Jamaica Union", "WITUC"),
    51: ("Interoceanic Mexican Union", "IOMU"),
    52: ("North Colombian Union", "CLUC"),
    53: ("North Mexican Union", "NMUC"),
    54: ("Panama Union", "PAMA"),
    55: ("Puerto Rican Union", "PRUC"),
    56: ("South Columbian Union", "SCOL"),
    57: ("Southeast Mexican Union", "SEMU"),
    58: ("West Venezuela Union", "SWVM"),
    59: ("Altantic Union", "ATUC"),
    60: ("Canadian Union", "SCIC"),
    61: ("Columbia Union", "COUC"),
    62: ("Lake Union", "LKUC"),
    63: ("Mid-America Union", "MAUC"),
    64: ("North Pacific Union", "NPACM"),
    65: ("Southern Union", "NSUC"),
    66: ("Southwestern Union", "SWUC"),
    67: ("Korean Union", "KRUC"),
    68: ("Taiwan Conference", "TWNM"),
    69: ("Mongolia Mission", "MGMF"),
    70: ("Japan Union", "JPUC"),
    71: ("Argentina Union", "ARGU"),
    72: ("Bolivia Union", "BLUM"),
    73: ("Central Brazil Union", "CBRC"),
    74: ("Chile Union", "CLUM"),
    75: ("Ecuador Union", "ECDU"),
    76: ("East Brazil Union", "EABR"),
    77: ("North Brazil Union", "NBUM"),
    78: ("Northeast Brazil Union", "NEBUM"),
    79: ("Northwest Brazil Union", "NWBR"),
    80: ("Paraguay Union", "PARU"),
    81: ("South Brazil Union", "SBUC"),
    82: ("South Peru Union", "SPEU"),
    83: ("Southeast Brazil Union", "EBUC"),
    84: ("Uruguay Union", "URUU"),
    85: ("West Central Brazil Union", "WCBU"),
    86: ("Australian Union", "AUSU"),
    87: ("New Zealand Union", "NZPU"),
    88: ("Papua New Guinea Union", "PNGUM"),
    89: ("Trans Pacific Union", "TPACU"),
    90: ("Botswana Union", "BOTU"),
    91: ("Indian Ocean Union", "IOUM"),
    92: ("Malawi Union", "MWUM"),
    93: ("Mozambique Union", "MZUM"),
    94: ("North-Eastern Angola Union", "NOAO"),
    95: ("Northern Zambia Union", "NZAM"),
    96: ("Southern Africa Union", "SAUC"),
    97: ("Southern Zambia Union", "SZAM"),
    98: ("South-Western Angola Union", "AGUM"),
    99: ("Zimbabwe Central Union", "ZIMC"),
    100: ("Zimbabwe East Union", "ZIME"),
    101: ("Zimbabwe Western Union", "ZIMW"),
    102: ("Sao Tome and Principe Union", "STPM"),
    103: ("East-Central India Section", "CIUS"),
    104: ("Northeast India Section", "NEIUS"),
    105: ("Northern India Section", "NIUS"),
    106: ("South-Central India Section", "KRNG"),
    107: ("Southeast India Section", "SIUS"),
    108: ("Southwest India Section", "KRLA"),
    109: ("Western India Section", "WIND"),
    110: ("Andaman and Nicobar Island Region", "ANIR"),
    111: ("East Himalayan Field", "EHIM"),
    112: ("Bangladesh Union", "BAUM"),
    113: ("Central Philippine Union", "CPUC"),
    114: ("East Indonesia Union", "EIUC"),
    115: ("Malaysia Union", "MALU"),
    116: ("Myanmar Union", "MYUM"),
    117: ("North Philippine Union", "NPUM"),
    118: ("Pakistan Union Section", "PKUS"),
    119: ("South Philippine Section", "SPS"),
    120: ("Southeastern Asia Union", "SEAUM"),
    121: ("West Indonesia Union", "WIUM"),
    122: ("Sri Lanka Mission", "SRIL"),
    123: ("Timor Leste Mission", "ETIM"),
    124: ("Singapore Conference", "SGPM"),
    125: ("Adriatic Union", "ADUC"),
    126: ("Baltic Union", "BAUC"),
    127: ("British Union", "BRUC"),
    128: ("Danish Union", "DUOC"),
    129: ("Finland Union", "FNUC"),
    130: ("Hungarian Union", "HUNC"),
    131: ("Netherlands Union", "NEUC"),
    132: ("Norwegian Union", "NRUC"),
    133: ("Polish Union", "POUC"),
    134: ("South-East European Union", "SEEUC"),
    135: ("Swedish Union", "SWDC"),
    136: ("Cyprus Union", "CYPS"),
    137: ("Greek Mission", "GRKM"),
    138: ("Iceland Union", "ICLC"),
    139: ("Cameroon Union", "CAUM"),
    140: ("Central African Union", "CEAF"),
    141: ("Eastern Nigeria Union", "ENUM"),
    142: ("Eastern Sahel Union", "SAUM"),
    143: ("Northern Nigeria Union", "NONI"),
    144: ("Southern Ghana Union", "GHUC"),
    145: ("West African Union", "WAUM"),
    146: ("West Nigeria Union", "NGUM"),
    147: ("Western Sahel Union", "WESA"),
    148: ("Hong Kong-Macao", "HKMC"),
    149: ("Egypt-Sudan Field", "EGYF"),
    150: ("East Mediterranean Region", "EMDF"),
    151: ("Gulf Field", "GUSS"),
    152: ("North Africa Region", "MAGS"),
    153: ("West Asia Field", "TRKS"),
}
