api_url = "https://orgmast.adventist.org/OrgMastAPI/api/OMAdmfield?$filter=Active%20eq%20true"

division_dict = {
    0: ("East-Central Africa Division", "ECD"),
    1: ("Euroasia Division", "ESD"),
    2: ("Intereuropean Division", "EUD"),
    3: ("Interamerican Division", "IAD"),
    4: ("North American Division", "NAD"),
    5: ("Northern Asia Pacific Division", "NSD"),
    6: ("South American Division", "SAD"),
    7: ("South Pacific Division", "SPD"),
    8: ("Southern African Indian Ocean Division", "SID"),
    9: ("Southern Asia Division", "SUD"),
    10: ("Southern Asia Pacific Division", "SSD"),
    11: ("Transeuropean Division", "TED"),
    12: ("West Central Africa Division", "WAD"),
    13: ("Chinese Union Mission", "CHUM"),
    14: ("Middle East North African Union Mission", "MENAUM"),
}
union_dict = {
    0: ("Burundi Union Mission", "BUM"),
    1: ("East Kenia Union Conference", "EKUC"),
    2: ("East Congo Union Mission", "ECUM"),
    3: ("Eastern Ethiopian Union Mission", "EEUM"),
    4: ("North East Congo Union Mission", "NECUM"),
    5: ("Northern Tanzania Union Mission", "NTUM"),
    6: ("Rwanda Union Mission", "RUM"),
    7: ("Suthern Tanzania Union Mission", "STUM"),
    8: ("Uganda Union Mission", "UUM"),
    9: ("West Congo Union Mission", "WCUM"),
    10: ("West Kenya Union Conference", "WKUC"),
    11: ("Western Ethiopia Union Mission", "WEUM"),
    12: ("South Sudan Attached Territory", "SSAT"),
    13: ("Eritea Mission Field", "EMF"),
    14: ("Belarus Union of Churches", "BUC"),
    15: ("Caucasus Union Mission", "CUM"),
    16: ("East Russian Union Mission", "ERUM"),
    17: ("Far Eastern Union of Chruches Mission", "FEUCM"),
    18: ("Moldova Union of Churches Conference", "MUCCC"),
    19: ("Southern Union Mission", "SUM"),
    20: ("West Russian Union Mission", "WRUM"),
    21: ("Armenian Field", "AF"),
    22: ("Crimea Field", "CF"),
    23: ("Don Field", "DF"),
    24: ("Georgian Field", "GF"),
    25: ("Austrian Union", "AU"),
    26: ("Bulgarian Union", "BU"),
    27: ("Czecho-SLovak Union", "CSU"),
    28: ("Franco-Belgian Union", "FBU"),
    29: ("Italian Union", "IU"),
    30: ("North German Union", "NGU"),
    31: ("Portuguese Union", "PU"),
    32: ("Romanian Union", "RU"),
    33: ("South German Union", "SGU"),
    34: ("Spanish Union", "SU"),
    35: ("Swiss Union", "SWU"),
    36: ("Atlantic Caribbean Union", "ACU"),
    37: ("Belize Union", "BU"),
    38: ("Caribbean Union", "CU"),
    39: ("Central Mexican Union", "CMU"),
    40: ("Chiapas Mexican Union", "CMU"),
    41: ("Cuban Union", "CU"),
    42: ("Dominican Union", "DU"),
    43: ("Dutch Caribbean Union", "DCU"),
    44: ("East Venezuela Union", "EVU"),
    45: ("El Salvador Union", "ESU"),
    46: ("French-Antilles-Guiana Union", "FAGU"),
    47: ("Guatemala Union", "GU"),
    48: ("Haitian Union", "HU"),
    49: ("Honduras Union", "HU"),
    50: ("Jamaica Union", "JU"),
    51: ("Interoceanic Mexican Union", "IMU"),
    52: ("North Colombian Union", "NCU"),
    53: ("North Mexican Union", "NMU"),
    54: ("Panama Union", "PU"),
    55: ("Puerto Rican Union", "PRU"),
    56: ("South Columbian Union", "SCU"),
    57: ("Southeast Mexican Union", "SEMU"),
    58: ("West Venezuela Union", "WVU"),
    59: ("Altantic Union", "AU"),
    60: ("Canadian Union", "CU"),
    61: ("Columbia Union", "CU"),
    62: ("Lake Union", "LU"),
    63: ("Mid-America Union", "MAU"),
    64: ("North Pacific Union", "NPU"),
    65: ("Southern Union", "SU"),
    66: ("Southwestern Union", "SWU"),
    67: ("Korean Union", "KU"),
    68: ("Taiwan Conference", "TC"),
    69: ("Mongolia Mission", "MM"),
    70: ("Japan Union", "JU"),
    71: ("Argentina Union", "AU"),
    72: ("Bolivia Union", "BU"),
    73: ("Central Brazil Union", "CBU"),
    74: ("Chile Union", "CU"),
    75: ("Ecuador Union", "EU"),
    76: ("East Brazil Union", "EBU"),
    77: ("North Brazil Union", "NBU"),
    78: ("Northeast Brazil Union", "NEBU"),
    79: ("Northwest Brazil Union", "NWBU"),
    80: ("Paraguay Union", "PU"),
    81: ("South Brazil Union", "SBU"),
    82: ("South Peru Union", "SPU"),
    83: ("Southeast BRazil Union", "SBU"),
    84: ("Uruguay Union", "UU"),
    85: ("West Central Brazil Union", "WCBU"),
    86: ("Australian Union", "AU"),
    87: ("New Zealand Union", "NZU"),
    88: ("Papua New Guinea Union", "PNGU"),
    89: ("Trans Pacific Union", "TPU"),
    90: ("Botswana Union", "BU"),
    91: ("Indian Ocean Union", "IOU"),
    92: ("Malawi Union", "MU"),
    93: ("Mozambique Union", "MU"),
    94: ("North-Eastern Angola Union", "NEAU"),
    95: ("Northern Zambia Union", "NZU"),
    96: ("Southern Africa Union", "SAU"),
    97: ("Southern Zambia Union", "SZU"),
    98: ("South-Western Angola Union", "SWAU"),
    99: ("Zimbabwe Central Union", "ZCU"),
    100: ("Zimbabwe East Union", "ZEU"),
    101: ("Zimbabwe Western Union", "ZWU"),
    102: ("Sao Tome and Principe Union", "STPU"),
    103: ("East-Central India Section", "ECIS"),
    104: ("Northeast India Section", "NEIS"),
    105: ("Northern India Section", "NIS"),
    106: ("South-Central India Section", "SCIS"),
    107: ("Southeast India Section", "SEIS"),
    108: ("Southwest India Section", "SWIS"),
    109: ("Western India Section", "WIS"),
    110: ("Andaman and Nicobar Island Region", "ANIR"),
    111: ("East Himalayan Field", "EHF"),
    112: ("Bangladesh Union", "BU"),
    113: ("Central Philippines Union", "CPU"),
    114: ("East Indonesia Union", "EIU"),
    115: ("Malasya Union", "MU"),
    116: ("Myanmar Union", "MU"),
    117: ("North Philippine Union", "NPU"),
    118: ("Pakistan Union Section", "PUS"),
    119: ("South Philippine Section", "SPS"),
    120: ("Southeastern Asia Union", "SEAU"),
    121: ("West Indonesia Union", "WIU"),
    122: ("Sri Lanka Mission", "SLM"),
    123: ("Timor Leste Mission", "TLM"),
    124: ("Singapore Conference", "SC"),
    125: ("Adriatic Union", "AU"),
    126: ("Blatic Union", "BU"),
    127: ("British Union", "BU"),
    128: ("Danish Union", "DU"),
    129: ("Finland Union", "FU"),
    130: ("Hungarian Union", "HU"),
    131: ("Netherlands Union", "NU"),
    132: ("Norwegian Union", "NU"),
    133: ("Polish Union", "PU"),
    134: ("South-East European Union", "SEEU"),
    135: ("Swedish Union", "SU"),
    136: ("Cyprus Union", "CU"),
    137: ("Greek Mission", "GM"),
    138: ("Iceland Union", "IU"),
    139: ("Cameroon Union", "CU"),
    140: ("Central African Union", "CAU"),
    141: ("Eastern Nigeria Union", "ENU"),
    142: ("Eastern Sahel Union", "ESU"),
    143: ("Northern Nigeria Union", "NNU"),
    144: ("Southern Ghana Union", "SGU"),
    145: ("West African Union", "WAU"),
    146: ("West Nigeria Union", "WNU"),
    147: ("Western Sahel Union", "WSU"),
    148: ("Hong Kong-Macao", "HKM"),
    149: ("Egypt-Sudan Field", "ESF"),
    150: ("East Mediterranean Region", "EMR"),
    151: ("Gulf Field", "GF"),
    152: ("North Africa Region", "NAR"),
    153: ("West Asia Field", "WAF"),
}
